node {
    git branch: 'master', url: '/home/projects/dicoding-submission-jenkins/simple-java-maven-app'
    
    withDockerContainer(args: '-v /root/.m2:/root/.m2', image: 'maven:3.9.0') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }
        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap Deploy?'
        }
        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'
            sleep time: 1, unit: 'MINUTES'
        }
    }
}
